/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        background: "#f4faff",
        surface: "#f4faff",
        "surface-dim": "#cfdce4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e9f6fd",
        "surface-container": "#e3f0f8",
        "surface-container-high": "#ddeaf2",
        "surface-container-highest": "#d7e4ec",
        "on-surface": "#111d23",
        "on-surface-variant": "#404752",
        "inverse-surface": "#263238",
        "inverse-on-surface": "#e6f3fb",
        "outline": "#707783",
        "outline-variant": "#c0c7d4",
        primary: "#005ea4",
        "primary-container": "#0077ce",
        "primary-fixed": "#d3e4ff",
        "primary-fixed-dim": "#a2c9ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fdfcff",
        secondary: "#3e6a00",
        "secondary-container": "#b9f474",
        "secondary-fixed": "#b9f474",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#437000",
        tertiary: "#b7131a",
        "tertiary-container": "#db322f",
        "tertiary-fixed": "#ffdad6",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        body: ["Atkinson Hyperlegible Next", "Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        lift: "0 4px 12px rgba(0, 0, 0, 0.05)",
        modal: "0 12px 24px rgba(0, 0, 0, 0.15)",
      },
      spacing: {
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
    },
  },
  plugins: [],
};
